### ISSUE TITLE
[Bug]: Creepers spawn in sky light

### ISSUE THREAD

**Issue by Raidobw2** [CreeperHost/ResoursefulCreepers#1]
### Modlist
![modlist](https://user-images.githubusercontent.com/17010632/165386054-49573ed1-7a38-4580-9947-a7fa11ac9293.png)

### Description
Resource Creepers will spawn in daylight, while their normal Creeper counterpart will spawn in darkness only (no skylight, no blocklight).
### Media

https://user-images.githubusercontent.com/17010632/165386924-5f68408f-2506-46a1-9941-03eeab409317.mp4

**Comment by Raidobw2** [comment]
After the fix they seem to not spawn at all in fact, this is with the new default config file as well:

https://user-images.githubusercontent.com/17010632/165637030-b83e04d4-90f8-4f8f-9ae9-c8d6638bcdd5.mp4

I've added Creativerite mod simply for no clip flight and test to see if I could see some through walls, but saw none unfortunately (it only adds like 10 items and that's it)

**Comment by gigabit101** [comment]
Spectator mode?? xD

**Comment by Raidobw2** [comment]
Can't use a spyglass in spectator mode to see if they despawn :P this is fixed, creepers don't spawn in neither block light or sky light.
Saw you added > 4 in code, that's alright with me (means they can spawn in caves more, due to the lush stuff making some light), so I'll go ahead and close this, thank you!
