### ISSUE TITLE
[Feature]: Creeper explosions should possibly not destroy armor stands

### ISSUE THREAD

**Issue by Raidobw2** [CreeperHost/ResoursefulCreepers#11]
### Modlist
![modlist](https://user-images.githubusercontent.com/17010632/165393943-1138124d-0f79-47ff-a3e6-3f4193463aba.png)

### Description
If a creeper explodes too close to an armor stand, they will destroy it. Armor stands are entities and can be destroyed by normal creeper explosions. This is a feature/question, I think that behavior should be debunked.

The armor stand is an excellent mechanic that's been added, however explosions themselves can render them useless, turning your automatic farm into a semi-automatic farm.

This means that drop farming is lower maintenance on the long term, and could be prioritized by players.
### Media

https://user-images.githubusercontent.com/17010632/165394333-98df5ec2-be06-462f-813c-36607e853645.mp4

**Comment by gigabit101** [comment]
It has a large radius, and when using it in automation, you would want to put it behind a wall/some sort of protection, but again this could be added as a config option depending on how difficult it will be to implement
