### ISSUE TITLE
Nether and End spawn rate is very high

### ISSUE THREAD

**Issue by Raidobw2** [CreeperHost/ResoursefulCreepers#14]
Creepers in the Nether and the End spawn a lot more than in the Overworld. Mods like InControl can change the spawning places of those creepers for pack developers.
Up to you if you want to support multiple dimension spawns (including custom ones) through config, or if you leave it to the Overworld and have InControl or things like KubeJS relocate spawns for pack makers. If you go config route `resourcefulcreepers_types.json` is the way to go I think, and people might request custom dimension support later as well, which you could add now if you want since it'll be done. <- that last point really opens up the mod for quicker pack making, which can be a selling point of the mod ;D
![image](https://user-images.githubusercontent.com/17010632/165644955-f8b6ba26-9b07-41bb-a4f1-8a31f2618242.png)
![image](https://user-images.githubusercontent.com/17010632/165644965-7dfe1145-27d2-4b9d-a8b8-23b93ebbdcd0.png)
![image](https://user-images.githubusercontent.com/17010632/165644975-342e3cb1-3c5a-46dc-aff0-a201308f4b03.png)

**Comment by gigabit101** [comment]
Creepers will now only spawn in the overworld, for now, I have added an issue to allow this to be configurable

**Comment by Raidobw2** [comment]
You fixed it, thank you!
![image](https://user-images.githubusercontent.com/17010632/165840799-b317e3b5-c7c8-4290-aeaa-3d559291df64.png)
![image](https://user-images.githubusercontent.com/17010632/165840811-a5105c02-03e2-4200-beb8-06e8e6903697.png)
