### ISSUE TITLE
Newly spawned creepers sometimes don't die or blow up

### ISSUE THREAD

**Issue by Raidobw2** [CreeperHost/ResoursefulCreepers#15]
I'm not sure about this one, but I saw some creepers that didn't blow up, and only one of them looked like it spawned blocks and launched itself in the air. Very weird, see attached videos:

https://user-images.githubusercontent.com/17010632/165648493-a7f203e9-8d5c-4190-838b-c3d413fc0631.mp4

https://user-images.githubusercontent.com/17010632/165648506-6c97872c-3bef-4ad2-8b93-91ab8ff353f0.mp4

**Comment by gigabit101** [comment]
There was a baby inside of it, Guess you hit it with the egg when spamming the spawns, The baby exploded casing the tiny pile, Forcing a baby to spawn with the egg will set the parent to tamed

**Comment by Raidobw2** [comment]
You're right, there looks to be a baby creeper under the redstone creeper. Thanks for having looked into it!
