### ISSUE TITLE
Creepers are not aggressive towards the player

### ISSUE THREAD

**Issue by Raidobw2** [CreeperHost/ResoursefulCreepers#17]
This is the continuation of #5. They are no longer aggressive when fed gunpowder, but they simply aren't aggressive at all towards the player. They will explode if the player gets close by to them, but will not pathfind to the player nor retaliate when attacked. Not sure if this is now intended or a bug!

https://user-images.githubusercontent.com/17010632/165649450-7a6b9e9d-893a-4731-a5cc-c1a6bec402b1.mp4

**Comment by gigabit101** [comment]
Right now when tamed they are non-hostile, They will not try and attack anything

**Comment by gigabit101** [comment]
If a player hurts a creeper its tamed status will be reset

**Comment by Raidobw2** [comment]
My previous example was with an untamed creeper. Here is another example to explain the behavior:

https://user-images.githubusercontent.com/17010632/165838527-28a41c88-d353-4631-9529-790131656d09.mp4

Also, using gunpowder on them doesn't make them passive. Is it intended?

https://user-images.githubusercontent.com/17010632/165838572-d47b9c43-6946-4c82-8276-c9e03664be4d.mp4

**Comment by gigabit101** [comment]
Did you remember to turn the config on to make them passive when tamed? I spent a lot of time fixing this AI today to make them also not swell when tamed and the config is on so I know it worked

**Comment by Raidobw2** [comment]
Oh, I forgot to turn on the config sorry! Yes they are passive with the config on now. The offspring is hostile however

https://user-images.githubusercontent.com/17010632/165863279-3090ad6d-3df9-4cd2-bc99-21f06b136651.mp4

**Comment by gigabit101** [comment]
Should be fixed, Minecraft being Minecraft

**Comment by Raidobw2** [comment]
They are now aggressive and the baby is tamed on spawn, so all is working! Minor detail, the creepers still follow you when tamed but you can't really make them sit. It feel it makes leashes useless but also a bit annoying if trying to get away from them in a pen, they could follow you outside the fences. Possibly they could simply stop following the player, or become attracted to the player when it holds their breeding item, gunpowder?

https://user-images.githubusercontent.com/17010632/166069062-29fc0eb7-1898-4692-b334-cf28c67140ce.mp4

**Comment by Raidobw2** [comment]
Edit: Deleted previous comment because I forgot to mute myself as I was recording 🤦 muted video audio and rewritten comment

They are now aggressive and the baby is tamed on spawn, so all is working! Minor detail, the creepers still follow you when tamed but you can't really make them sit. It feel it makes leashes useless but also a bit annoying if trying to get away from them in a pen, they could follow you outside the fences. Possibly they could simply stop following the player, or become attracted to the player when it holds their breeding item, gunpowder?

https://user-images.githubusercontent.com/17010632/166071993-16102939-8918-40d5-9b81-4d236d7ba203.mp4

**Comment by gigabit101** [comment]
Fixed in 1.0.12

**Comment by Raidobw2** [comment]
Yup, works perfectly now thank you. That's awesome!
