### ISSUE TITLE
Creeper explosions seem to only replace grass blocks and others replaceables

### ISSUE THREAD

**Issue by Raidobw2** [CreeperHost/ResoursefulCreepers#20]
Hello :)

-Mod versions-
Minecraft `1.18.2`
Forge `40.1.20`
polylib: `polylib-forge-1801.0.2-build.13.jar`
resourcefulcreepers: `resourcefulcreepers-forge-1.18.2-1.0.12.jar`

The creepers seems to replace only grass blocks (replaceables) now, i'm not sure what's happening, here's a video:

https://user-images.githubusercontent.com/17010632/170197247-e2e48a52-ad5d-4877-8141-6ddf921e56ac.mp4

This is the config I have:
```
{
  "generateDefaultTypes": false,
  "autoGenerateCreeperTypesFromOreTags": false,
  "explosionMultiplier": 1,
  "poweredExplosionMultiplier": 0.5,
  "explosionsGenerateOres": true,
  "overrideOreDrops": false,
  "creepersAttractedToArmourStand": true,
  "disableSentry": false,
  "nonHostileWhenTamed": true
}
```

Thanks in advance for checking it out!

P.S. CurseForge last version shown is 1.0.5, 1.0.12+ is not public yet

**Comment by gigabit101** [comment]
Works fine for me, Guessing something is breaking isAir()

**Comment by Saereth** [comment]
This is happened when roadrunner mod is added, removing it resolves the issue, I suspect perhaps a mixin incompatibility with one of our other performance increasing mods I reproduced it with this minimal modlist

![image](https://user-images.githubusercontent.com/9200909/170331898-eaf9dcdc-acc3-40a4-b4b3-3e0f66f6d3db.png)

**Comment by Raidobw2** [comment]
This is fixed, thank you very much gigabit101
