### ISSUE TITLE
Tamed/Bred Creepers despawn (Plexiglass Mountain modpack 1.1.1 Server)

### ISSUE THREAD

**Issue by ariosos** [CreeperHost/ResoursefulCreepers#23]
1. Tame and/or breed a resourceful creeper.
2. Leave the tamed and newborn creepers and leave the area (more than 128 blocks.
3. Return to the area.

Observed Result: The resourceful creepers despawn. I think this may be related to the "creepers don't despawn" bug fix awhile back.

**Comment by Joly0** [comment]
I am having a similar issue, but not quite the same. I am playing the same Modpack and i have setup a farm using the soul shards mod and its spawner. Though, all the creepers instantly despawn, if i am not close to the spawner.
