### ISSUE TITLE
Thermal Series Tin Ore Missing

### ISSUE THREAD

**Issue by githubuser1256** [CreeperHost/ResoursefulCreepers#24]
Hello,

I'm using the latest FTB Plexiglass Mountain modpack. The Thermal Series' Tin Ore is missing as one of the creepers. Is this because CoFH (Thermal Series team) has neglected to properly implement tin or is this a modification you need to make?

Thanks.

**Comment by gigabit101** [comment]
This will be because it was not added to the config or it does not have the ores tag so we can't auto-generate it
