### ISSUE TITLE
You should let people know that you track players environment with your mod

### ISSUE THREAD

**Issue by JaisDK** [CreeperHost/ResoursefulCreepers#25]
As the title says. I don't see it disclosed anywhere that you're collecting environment data from the user.

https://github.com/CreeperHost/ResourcefulCreepers/blob/master/common/src/main/java/net/creeperhost/resourcefulcreepers/ResourcefulCreepers.java#L36

**Comment by gigabit101** [comment]
https://www.creeperhost.net/blog/our-use-of-sentry-and-data-collection/
