### ISSUE TITLE
[Feature]: Reduce base spawn rate

### ISSUE THREAD

**Issue by Raidobw2** [CreeperHost/ResoursefulCreepers#3]
### Modlist
![modlist](https://user-images.githubusercontent.com/17010632/165388796-227fb3dc-91e2-404d-8453-7dda01608b39.png)

### Description
I know the mod is configurable for modpack makers, but please consider reducing the shipped base spawn rate.

With issues #1 and #2, your world will fill extremely quickly of resource creepers.
### Media

https://user-images.githubusercontent.com/17010632/165388958-8d098467-4ca3-4f93-9c88-aaf090ac5d5e.mp4

In the above video, my back isn't shown. Here's what was in my back:
![swamp](https://user-images.githubusercontent.com/17010632/165388979-ee2de3a9-4666-42fa-b6fc-a2536527d075.png)

**Comment by Raidobw2** [comment]
I've tweaked some spawns with InControl in one of my tests, and a base weight of 10 or 20 distributed among all creepers would probably be good. They'd need some kind of mob cap though, possibly fitting into the hostile mob cap if that's doable at all.

In my tests they had about that weight but the mob cap was 5. Meaning only 5 creepers could exist at one given time. I think the mod by default could have a (configurable) mob cap for those creepers of probably 10 per player, that would be reasonable.

**Comment by gigabit101** [comment]
Might be fixed with the changes to spawn logic, Not able to find anything to do with weight in 1.18s spawn logic so the value we are giving it is not even being used

**Comment by Raidobw2** [comment]
Can't test for now, see #1 :P

**Comment by Raidobw2** [comment]
The overworld base spawn rate is perfect in my opinion. It almost looks like it replaces part of the creepers, which is very cool!
Nether and End rates are a different thing, but the Overworld is fixed for sure. I'll make a new issue for Nether and End. Thanks again!
![image](https://user-images.githubusercontent.com/17010632/165644133-fa4e07b5-1448-4b07-a7f8-f8ecb73eba72.png)
![image](https://user-images.githubusercontent.com/17010632/165644140-c22f301c-28f6-421a-a052-43647b6ee82b.png)
![image](https://user-images.githubusercontent.com/17010632/165644174-3877d926-e3f1-4e01-9d04-3f40e00cd872.png)
![image](https://user-images.githubusercontent.com/17010632/165644183-ffca3464-9d28-48c2-90fd-86943b867b47.png)
![image](https://user-images.githubusercontent.com/17010632/165644198-26e326a2-9f5d-4d9c-bf3b-67d1f71e18f0.png)
![image](https://user-images.githubusercontent.com/17010632/165644207-7b3fb7c3-547b-40f5-9568-64abbf44194f.png)
