### ISSUE TITLE
[Bug]: Explosions sometimes leave ghost blocks behind

### ISSUE THREAD

**Issue by Raidobw2** [CreeperHost/ResoursefulCreepers#4]
### Modlist
![modlist](https://user-images.githubusercontent.com/17010632/165389274-6027ee4f-c463-4233-87e3-65e94c74b9a2.png)

### Description
Explosions from Resource Creepers sometimes leave behind ghost blocks, which can leave a player confused.

This happens randomly, but I may have had more success in reproducing this with naturally spawned creepers. Not sure if that is a coincidence.
### Media

https://user-images.githubusercontent.com/17010632/165389444-346dfecf-eaf4-4b49-b2ab-33ad85c0b4d7.mp4

**Comment by gigabit101** [comment]
No idea why this is happening, Not once had this happen to me

**Comment by Raidobw2** [comment]
I couldn't replicate the weird ghost blocks after the fix! 🙌 although once but only once I did hear the "boom". Although that's very minor and only happened once out of like 300 creepers. I'll leave this open in case you want to check anything else about it, but for me that's considered fixed, you can close this one, thanks

https://user-images.githubusercontent.com/17010632/165648202-01863875-4f42-4d2e-8a57-ffd576d8c4e1.mp4

**Comment by Raidobw2** [comment]
Actually, disregard the remaining sound issue in here, it will be fixed in #9. Ghost blocks are fixed, thanks!
