### ISSUE TITLE
[Feature]: Creepers are still being aggressive after being fed gunpowder

### ISSUE THREAD

**Issue by Raidobw2** [CreeperHost/ResoursefulCreepers#5]
### Modlist
![modlist](https://user-images.githubusercontent.com/17010632/165390011-2639737a-e0d7-41d6-a611-28a319fd49ed.png)

### Description
If you feed a Resource Creeper gunpowder, it will not be tame and still be aggressive. It will then explode on you.
### Media

https://user-images.githubusercontent.com/17010632/165390104-3bd3d3f0-437e-487b-ba74-689b072fe4fb.mp4

**Comment by Raidobw2** [comment]
Note that this renders breeding them in survival mode almost impossible if trying to breed them "normally". You'd need a cage for the creepers, which isn't intuitive and newbie friendly in my opinion. They somehow seem to continue swelling a bit more and explode after feeding them gunpowder as well, but this should be resolved with the tame mechanic.

https://user-images.githubusercontent.com/17010632/165390398-342a1a4c-e1a4-42be-8241-e528a40547f7.mp4

**Comment by Raidobw2** [comment]
Here is another example below! To note that newborn babies also are not tame, which means that they will also try to blow up when they see you.

https://user-images.githubusercontent.com/17010632/165391045-e2f6a6e4-e323-4f37-944b-6cd42eaa3ca3.mp4

`[26Apr2022 15:33:58.231] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [CHAT] Name has the following entity data: {Brain: {memories: {}}, HurtByTimestamp: 0, Attributes: [{Base: 15.0d, Modifiers: [{Amount: 0.0526192156718312d, Operation: 1, UUID: [I; 828675728, 1010517741, -1570980380, -1705414863], Name: "Random spawn bonus"}], Name: "minecraft:generic.follow_range"}, {Base: 0.08d, Name: "forge:entity_gravity"}, {Base: 0.25d, Name: "minecraft:generic.movement_speed"}], Invulnerable: 0b, FallFlying: 0b, ForcedAge: 0, PortalCooldown: 0, AbsorptionAmount: 0.0f, FallDistance: 0.0f, InLove: 389, CanUpdate: 1b, DeathTime: 0s, HandDropChances: [0.085f, 0.085f], PersistenceRequired: 1b, UUID: [I; 1721208216, -2088482134, -1547260088, -561525067], Age: 0, Fuse: 30s, Motion: [0.046799841457415434d, -0.0784000015258789d, -0.004276477301357072d], Health: 20.0f, LeftHanded: 0b, Air: 300s, OnGround: 1b, ignited: 0b, Rotation: [265.62915f, -40.0f], HandItems: [{}, {}], tamed: 0b, ArmorDropChances: [0.085f, 0.085f, 0.085f, 0.085f], CustomName: '{"text":"Name"}', Pos: [45.359953609935175d, 65.0d, 483.5094234087598d], Fire: -1s, ArmorItems: [{}, {}, {}, {}], CanPickUpLoot: 0b, HurtTime: 0s, LoveCause: [I; 1724885654, 1900101746, -1132350945, 1611876893], ExplosionRadius: 3b}`

-> `tamed: 0b`

**Comment by gigabit101** [comment]
Currently, tamed only stops them from despawning when changing to peaceful. There were no plans on making them non-hostile in the original design of the mod, but it might get added as a config option

**Comment by Raidobw2** [comment]
I misunderstood that then! I thought they could be easily bred afterwards, thanks for the answer

**Comment by Raidobw2** [comment]
Yes they are no longer aggressive when fed gunpowder, although they also were not aggressive at first. That's another issue, so I'll close this one as fixed and the next one above should contain more information to that new error
