### ISSUE TITLE
[Bug]: Creeper explosions don't replace replaceables such as grass

### ISSUE THREAD

**Issue by Raidobw2** [CreeperHost/ResoursefulCreepers#7]
### Modlist
![modlist](https://user-images.githubusercontent.com/17010632/165392107-24dd06bb-a8fc-41de-8c31-e59e8ab0a7c1.png)

### Description
Resource Creeper explosions do not replace grass, fern blocks, etc. which they probably should.
### Media

https://user-images.githubusercontent.com/17010632/165392228-6485538b-1503-45ea-a8b8-263ba19dd389.mp4

**Comment by gigabit101** [comment]
Easy fix, Currently only checks for air blocks. Forgot about replaceable

**Comment by Raidobw2** [comment]
Yup that is fixed. Thanks a bunch! :D

https://user-images.githubusercontent.com/17010632/165650396-618b7d99-ddbb-4787-a940-7e9f5ec5499f.mp4
