### ISSUE TITLE
[Bug]: Creeper explosion has no sound

### ISSUE THREAD

**Issue by Raidobw2** [CreeperHost/ResoursefulCreepers#9]
### Modlist
![modlist](https://user-images.githubusercontent.com/17010632/165393188-b97f9df1-754a-4b17-b942-70f60a689112.png)

### Description
The explosion of a Resource Creeper has no sound. I suggest that a sound be added (or the normal creeper explosion sound be used), as it is an indicator that something happened and the environment changed
### Media

https://user-images.githubusercontent.com/17010632/165393305-f19d60ad-bd99-4f11-838d-91e7e0d4bec4.mp4

**Comment by Raidobw2** [comment]
Hmm, it doesn't seem to be playing in `1.0.7`, here is a short video

https://user-images.githubusercontent.com/17010632/165650778-583911f5-ba76-4868-959d-020315037dff.mp4

:

**Comment by Raidobw2** [comment]
This is still an issue on `1.0.8`, sometimes they make sounds, sometimes they don't at all

**Comment by ThePaul-T** [comment]
I doubt we will be able to find this in a reasonable timeframe as we are not able to consistently reproduce this. Any higher priority or blockers?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Raidobw2** [comment]
Yes, #17 would be the last, the rest no matter if they get fixed or not I can work around the issues until they are fixed. Issues with spawning was the biggest one (#1) and gigabit101 nailed it, the spawn mechanic is perfect now!

**Comment by gigabit101** [comment]
I don't understand, Sound played every time for me in dev and is played the exact same way as a vanilla creepers explosion

**Comment by Raidobw2** [comment]
I'm unsure but it looks like when they are tamed and they get punched, the sound plays everytime. Although when they are naturally spawned or with a spawn egg, I didn't get a sound from the explosion

https://user-images.githubusercontent.com/17010632/165863506-1919f1e9-434f-4f15-8d0c-d6cde90f60a9.mp4

**Comment by gigabit101** [comment]
Should be fixed in the latest build

**Comment by Raidobw2** [comment]
Yup, that works 100% of the time, my thanks to you and Paul for that fix!
